---

- name: Install EPEL repository from repo
  yum:
    name: epel-release

- name: Install packages with yum
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - python-pip
      - python-devel
      - gcc
      - cairo-devel
      - pycairo
      - bitmap-fonts-compat
      - libselinux-python
      - fontconfig
      - sudo
      - libffi-devel

- name: Install uwsgi with pip
  pip:
    name: uwsgi

- name: Install systemd unit carbon-cache.service
  template:
    src: carbon_cache_systemd.j2
    dest: /etc/systemd/system/carbon-cache.service
  register: ccunit

- name: Reload systemd if unit file has changed
  shell: systemctl daemon-reload
  when: ccunit is changed
  notify: restart carbon-cache

- name: Install systemd unit carbon-relay.service
  template:
    src: carbon_relay_systemd.j2
    dest: /etc/systemd/system/carbon-relay.service
  register: ccunit

- name: Reload systemd if unit file has changed
  shell: systemctl daemon-reload
  when: ccunit is changed
  notify: restart carbon-relay

- name: Install uwsgi default settings
  template:
    src: redhat_uwsgi_default.ini.j2
    dest: /etc/uwsgi_default.ini
  notify: restart uwsgi

- name: Install uwsgi graphite config
  template:
    src: uwsgi_graphite.ini.j2
    dest: /etc/uwsgi_graphite.ini
  notify: restart uwsgi

- name: Install systemd unit uwsgi.service
  template:
    src: uwsgi_systemd.j2
    dest: /etc/systemd/system/uwsgi.service
  register: uwsgiunit

- name: Reload systemd if unit file has changed
  shell: systemctl daemon-reload
  when: uwsgiunit is changed
  notify: restart uwsgi
